import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';
import Link from 'next/link';
import { Providers } from "@/redux/provider";
import { useState } from "react";
import Modal from "@/components/Modal/Modal";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Providers>
    <html lang="en">
      <body className={inter.className}>
        <div className="container">
          <nav className="navbar navbar-expand-lg navbar-light bg-light">
            <div className="collapse navbar-collapse">
              <ul className="navbar-nav mr-auto">
                <li className="nav-item active"><Link href="/" className="nav-link">Accueil</Link></li>
              </ul>
            </div>
          </nav>
        </div>
        <div className="container">
          {children}
        </div>
      </body>
    </html>
    </Providers>
  );
}
